React-Login-Demo
Kommunicate-io/Kommunicate-Web-SDK pull request #1169
Opened 2024-02-16 09:17 UTC by aditya822024

### What do you want to achieve?
- Every time a new user logs in with their new email ID, the new chat widget should open, logging out the old chat widget.

### PR Checklist

- [ ] I have tested it locally and all functionalities are working fine.
- [ ] I have compared it with mocks and all design elements are the same.
- [ ] I have tested it in IE Browser.

NOTE: Make sure you're comparing your branch with the correct base branch

2024-02-16 15:13 UTC, prochnost04 requested changes
This solution will confuse the customer

2024-02-19 05:19 UTC, panwaranuj01 requested changes

2024-02-19 05:19 UTC, panwaranuj01 commented on example/React-Demo/src/chat.js
> +import React from "react";
add one import statement

2024-02-19 05:22 UTC, panwaranuj01 requested changes

2024-02-19 05:22 UTC, panwaranuj01 commented on example/React-Demo/src/chat.js
> +      if ((mail ?? "").length > 0) {
we can simplify this

2024-02-19 05:24 UTC, panwaranuj01 requested changes
First file it for the `development` branch @aditya822024

2024-02-19 05:25 UTC, panwaranuj01 requested changes

2024-02-19 05:25 UTC, panwaranuj01 commented on example/React-Demo/package.json
> +  "private": true,
Is it required?

2024-02-19 05:25 UTC, panwaranuj01 commented on example/React-Demo/package.json
> +    "@kommunicate/kommunicate-chatbot-plugin": "0.0.7",
If you are not using this we can remove this as well

2024-02-27 05:51 UTC, panwaranuj01 commented
@aditya822024 If it's not needed then please close this pr.

2024-02-27 05:56 UTC, devashishmamgain commented
It is needed as a demo link to share with customers in future if anyone
asks for it.
we can remove the unnecessary files from it, and keep only the relevant
ones, along with a readme.md file that explains the concept

On Tue, 27 Feb 2024 at 11:21, Anuj Panwar ***@***.***> wrote:

> @aditya822024 <https://github.com/aditya822024> If it's not needed then
> please close this pr.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Kommunicate-io/Kommunicate-Web-SDK/pull/1169#issuecomment-1965836024>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABG7RQ4KPS2GKA23HQ5MKDYVVX67AVCNFSM6AAAAABDLWFIM2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSNRVHAZTMMBSGQ>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2024-03-24 00:36 UTC, closed without merging