function for user location
Kommunicate-io/Kommunicate-Web-SDK pull request #1188
Opened 2024-05-23 07:01 UTC by thakaresakshi121

### What do you want to achieve?
- get location of user

### PR Checklist

- [x] I have tested it locally and all functionalities are working fine.
- [ ] I have compared it with mocks and all design elements are the same.
- [ ] I have tested it in IE Browser.

### How was the code tested?

-

### What new thing you came across while writing this code? 
-

### In case you fixed a bug then please describe the root cause of it? 
-

### Screenshot
- 

NOTE: Make sure you're comparing your branch with the correct base branch

2024-05-23 07:05 UTC, devashishmamgain requested changes

2024-05-23 07:05 UTC, devashishmamgain commented on webplugin/js/app/kommunicate.js
> +          const response = await fetch(`https://api.geoapify.com/v1/geocode/reverse?lat=${position.coords.latitude}&lon=${position.coords.longitude}&format=json&apiKey=8ce8e23a726b474cb13a056bd31dd07
Pls use Google maps, remove geoapify

2024-05-23 07:28 UTC, panwaranuj01 requested changes

2024-05-23 07:28 UTC, panwaranuj01 commented on webplugin/js/app/kommunicate.js
> +          new Promise((resolve, reject) =>
We already have the `latitude` and `longitude` global variables use those variables.

2024-05-23 07:28 UTC, panwaranuj01 commented on webplugin/js/app/kommunicate.js
> +    getUserLocation:async function (){
put this function in mckMapService

2024-05-23 10:53 UTC, panwaranuj01 commented
@thakaresakshi121 Base should `development` branch

2024-05-27 08:21 UTC, thakaresakshi121 commented on webplugin/js/app/kommunicate.js
> +          const response = await fetch(`https://api.geoapify.com/v1/geocode/reverse?lat=${position.coords.latitude}&lon=${position.coords.longitude}&format=json&apiKey=8ce8e23a726b474cb13a056bd31dd07
updated  google map API

2024-05-28 08:34 UTC, thakaresakshi121 commented
raised Different PR (#1190 ) hence not needed

2024-05-28 08:34 UTC, closed without merging