added image-preview for rich message image CUS-223
Kommunicate-io/Kommunicate-Web-SDK pull request #1201
Opened 2024-07-10 08:19 UTC by thakaresakshi121

### What do you want to achieve?
-added image preview for rich message images in a bot response.

### PR Checklist

- [x] I have tested it locally and all functionalities are working fine.
- [ ] I have compared it with mocks and all design elements are the same.
- [ ] I have tested it in IE Browser.

### How was the code tested?

-

### What new thing you came across while writing this code? 
-

### In case you fixed a bug then please describe the root cause of it? 
-

### Screenshot
- 

https://github.com/Kommunicate-io/Kommunicate-Web-SDK/assets/169023124/916593b6-1628-4d79-817e-dcfaea915eb6

NOTE: Make sure you're comparing your branch with the correct base branch

2024-07-11 05:35 UTC, panwaranuj01 requested changes

2024-07-11 05:41 UTC, thakaresakshi121 commented on webplugin/js/app/km-richtext-markup-1.0.js
> +        <a href="#" target="_self" role="link" class="file-preview-link fancybox-media fancybox-kommunicate" data-type="image/png" data-url="{{url}}" data-name="{{caption}}">
In payload, we are only passing image URL and caption

2024-07-11 05:53 UTC, panwaranuj01 commented on webplugin/js/app/km-richtext-markup-1.0.js
> +        <a href="#" target="_self" role="link" class="file-preview-link fancybox-media fancybox-kommunicate" data-type="image/png" data-url="{{url}}" data-name="{{caption}}">
In the caption, white spaces like this `The Lion` can be included.

we have to remove the white space from there like this `the-lion`

2024-07-18 08:32 UTC, thakaresakshi121 commented on webplugin/js/app/km-richtext-markup-1.0.js
> +        <a href="#" target="_self" role="link" class="file-preview-link fancybox-media fancybox-kommunicate" data-type="image/png" data-url="{{url}}" data-name="{{caption}}">
@panwaranuj01 when I am passing the caption directly as  value to data-name it works fine and it shows the caption below the image.
![Screenshot 2024-07-18 134700](https://github.com/user-attachments/assets/ae8cda01-16fb-431d-a25a-676d9b6cdf4f)

and if I am trying to change the caption in this format  `image-name`  then it is not visible below image.
![Screenshot 2024-07-18 135239](https://github.com/user-attachments/assets/a25b52c6-4142-4355-a132-ea1b20ec76c4)

should I change it or keep it as it is?

2024-07-18 12:26 UTC, panwaranuj01 approved these changes

2024-07-22 06:17 UTC, merged