Chat widget changes to show the queue part
Kommunicate-io/Kommunicate-Web-SDK pull request #547
Opened 2020-09-11 10:49 UTC by Kusum-Dhoundiyal

### What do you want to achieve?
-Chat widget changes to show the queue part

### PR Checklist

- 
![Screenshot 2020-09-11 at 4 15 13 PM](https://user-images.githubusercontent.com/24999994/92915610-5b9d1580-f44a-11ea-87af-09bee0d2d3a3.png)
x] I have tested it locally and all functionalities are working fine.
- [ ] I have compared it with mocks and all design elements are the same.
- [ ] I have tested it in IE Browser.

### How was the code tested?

-

### What new thing you came across while writing this code? 
-

### In case you fixed a bug then please describe the root cause of it? 
-

NOTE: Make sure you're comparing your branch with the correct base branch

2020-09-11 10:58 UTC, devashishmamgain requested changes

2020-09-11 10:58 UTC, devashishmamgain commented on webplugin/template/mck-sidebox.html
> +                <div id = "mck-waiting-queue">You are currently in the waiting queue, our agents will get back you shortly. </div>
please make a habit of using MCK_LABELS

2020-09-11 11:06 UTC, devashishmamgain requested changes

2020-09-11 11:06 UTC, devashishmamgain commented on webplugin/js/app/km-utils.js
> +    CONVERSATION_STATE: {
these constants are present in km-conversation-helper.js

2020-09-11 12:19 UTC, akshatdhabi commented on webplugin/css/app/mck-sidebox-1.0.css
> +	color: #5C6677;
Check code formatting

2020-09-11 12:44 UTC, akshatdhabi commented
![image](https://user-images.githubusercontent.com/34703178/92926926-6b245a80-f45a-11ea-8aa8-a7242cf80082.png)

![image](https://user-images.githubusercontent.com/34703178/92926948-737c9580-f45a-11ea-903b-1a3cfb624b92.png)

![image](https://user-images.githubusercontent.com/34703178/92926957-78414980-f45a-11ea-8d7f-79483716eb62.png)



Please check the dropdown UI and also default is supposed to be set to 5

2020-09-11 13:56 UTC, devashishmamgain requested changes

2020-09-11 13:56 UTC, devashishmamgain commented on webplugin/js/app/km-utils.js
> +    CONVERSATION_WAITING_STATUS:'WAITING',
others are in lowercase, this one is in CAPS, whats the reason?

2020-09-11 13:56 UTC, devashishmamgain commented on webplugin/js/app/mck-sidebox-1.0.js
> +                            resp.message.metadata.KM_STATUS == KommunicateConstants.CONVERSATION_WAITING_STATUS   ?KommunicateUI.handleWaitingQueueMessage(true):KommunicateUI.handleWaitingQueueMessag
simplify this

2020-09-11 14:14 UTC, ab14bhardwaj commented on webplugin/js/app/kommunicate-client.js
> +                    response && response.data.metadata.CONVERSATION_STATUS ==Kommunicate.conversationHelper.status.WAITING ?KommunicateUI.handleWaitingQueueMessage(true):KommunicateUI.handleWaitingQu
let waitingStatus = response && response.data.metadata.CONVERSATION_STATUS ==Kommunicate.conversationHelper.status.WAITING;
KommunicateUI.handleWaitingQueueMessage(waitingStatus);

2020-09-14 05:09 UTC, devashishmamgain requested changes

2020-09-14 05:09 UTC, devashishmamgain commented on webplugin/js/app/kommunicate-client.js
>                      }
Same check is present at 3 places, see if directly the status value can be passed to the function. And that function can internally check this part

2020-09-14 06:33 UTC, devashishmamgain approved these changes

2020-09-15 08:35 UTC, ab14bhardwaj submitted a review, later dismissed

2020-09-18 09:21 UTC, devashishmamgain approved these changes

2020-09-18 09:37 UTC, ab14bhardwaj commented on webplugin/js/app/kommunicate-ui.js
> +            mckUtils.ajax({
@Kusum-Dhoundiyal We use below function to make requests in web-SDK.
``` 
 window.Applozic.ALApiService.ajax({
```

2020-09-18 09:38 UTC, ab14bhardwaj commented on webplugin/js/app/kommunicate-ui.js
> +
@Kusum-Dhoundiyal Check the response code is "success" or not if coming.
If nothing is coming to verify if the API was successful or not then you can resolve my comment.

2020-09-18 09:39 UTC, ab14bhardwaj commented on webplugin/js/app/kommunicate-ui.js
> +                    console.log('Error while fetching waiting list', err);
We remove console.log while minification, so please throw the error.

2020-09-18 09:39 UTC, ab14bhardwaj commented on webplugin/template/mck-sidebox.html
> +				</div>
Please format the code, if it's formatted then resolve the comment.

2020-09-18 09:40 UTC, ab14bhardwaj commented on webplugin/template/mck-sidebox.html
> +				</div>
Plus give a proper name to the ids by the name you have given I am not able to understand anything.

2020-09-18 09:42 UTC, ab14bhardwaj commented on webplugin/js/app/labels/default-labels.js
> +        'last.part': ' in the waiting queue, our agents will get back you shortly.'},
"waiting.queue.message" or "waiting.queue.heading"
The label name should be self-explanatory as the customers will use it.

NOTE: Please create the PR in docs repo also to add these labels.

2020-09-18 09:44 UTC, ab14bhardwaj commented on webplugin/js/app/kommunicate-ui.js
> +                    document.getElementById('mck-waiting-queue-2') && (document.getElementById('mck-waiting-queue-2').innerHTML = "#" + parseInt(WAITING_QUEUE.indexOf(parseInt(groupId)) + 1));
Check if the status code or message "success" is available in the API to verify if results are properly fetched or not.

2020-09-18 11:25 UTC, ab14bhardwaj approved these changes

2020-09-18 11:39 UTC, akshatdhabi approved these changes

2020-09-18 11:43 UTC, ab14bhardwaj commented
@devashishmamgain Merging the PR as you review it earlier, the review was dismissed automatically as per Kusum.

2020-09-18 11:43 UTC, merged