FW-1953 Pre-Chat lead form - Dropdown list on Web
Kommunicate-io/Kommunicate-Web-SDK pull request #637
Opened 2021-03-16 08:21 UTC by Ojashwa

### What do you want to achieve?

- Create a dropdown list for a pre-chat lead form field.

### PR Checklist

- [x] I have tested it locally and all functionalities are working fine.
- [ ] I have compared it with mocks and all design elements are the same.
- [ ] I have tested it in IE Browser.

### How was the code tested?

- Load installation script with preLeadCollection as suggested in the below image.

- Check a dropdown for that field will appear in the chat widget.
---
![image](https://user-images.githubusercontent.com/22856546/111276173-11952680-865d-11eb-8794-437642d3aa5a.png)
### What new thing you came across while writing this code? 
-

### In case you fixed a bug then please describe the root cause of it? 
-

NOTE: Make sure you're comparing your branch with the correct base branch

2021-03-16 08:34 UTC, devashishmamgain requested changes

2021-03-16 08:34 UTC, devashishmamgain commented on webplugin/js/app/mck-sidebox-1.0.js
> +                        var setDropDown = _this.createSelectFieldDropdown(
dropDownOptionsdropDownOptions and setDropDown variable is not required, as it is used only once, directly use 
kmChatInput = _this.createSelectFieldDropdown(preLeadCollection.options, kmChatInput);

2021-03-16 08:34 UTC, devashishmamgain commented on webplugin/js/app/mck-sidebox-1.0.js
> +                    'Please select ' +
use MCK_LABELS for 'Please select' so that customers can configure it if they wish to change the text

2021-03-16 10:47 UTC, devashishmamgain requested changes

2021-03-16 10:47 UTC, devashishmamgain commented on webplugin/js/app/labels/default-labels.js
> +    'select.option': 'Please select',
See if there is any labels for pre chat lead collection, put it under them

2021-03-16 13:08 UTC, devashishmamgain requested changes
Verify naming convention used in labels

2021-03-16 13:50 UTC, devashishmamgain approved these changes

2021-03-17 08:06 UTC, Prochnost55 approved these changes

2021-03-18 16:24 UTC, Prochnost55 requested changes

2021-03-18 16:24 UTC, Prochnost55 commented on webplugin/js/app/mck-sidebox-1.0.js
> +                            element.value.charAt(0).toUpperCase() +
remove arrow function

2021-03-18 17:47 UTC, devashishmamgain submitted a review, later dismissed

2021-03-19 04:51 UTC, Prochnost55 submitted a review, later dismissed

2021-03-24 05:24 UTC, Prochnost55 commented
Resolve the merge conflict

2021-03-24 08:51 UTC, devashishmamgain approved these changes

2021-03-25 05:30 UTC, Prochnost55 submitted a review, later dismissed

2021-04-06 08:57 UTC, Prochnost55 requested changes

2021-04-06 08:57 UTC, Prochnost55 commented on webplugin/js/app/mck-sidebox-1.0.js
>                  }
avoid use of jquery in new code

2021-04-06 09:14 UTC, Prochnost55 commented on webplugin/js/app/mck-sidebox-1.0.js
>                  }
Ok

2021-04-06 09:14 UTC, Prochnost55 approved these changes

2021-04-06 20:23 UTC, devashishmamgain approved these changes

2021-04-06 20:24 UTC, devashishmamgain commented
@Ojashwa how ill this drop down value be shown in the dashboard conversation section? can you please add a screenshot of it.

2021-04-07 05:05 UTC, Ojashwa commented
> @Ojashwa how ill this drop down value be shown in the dashboard conversation section? can you please add a screenshot of it.

![image](https://user-images.githubusercontent.com/22856546/113813157-fcf40c00-978c-11eb-8509-2f2d908ed529.png)

2021-04-07 05:11 UTC, merged