FW-2052 Access files signed URL in web plugin [Security, Important] [WIP]
Kommunicate-io/Kommunicate-Web-SDK pull request #653
Opened 2021-04-11 05:12 UTC by Prochnost55

### What do you want to achieve?
-

### PR Checklist

- [ ] I have tested it locally and all functionalities are working fine.
- [ ] I have compared it with mocks and all design elements are the same.
- [ ] I have tested it in IE Browser.

### How was the code tested?

-

### What new thing you came across while writing this code? 
-

### In case you fixed a bug then please describe the root cause of it? 
-

NOTE: Make sure you're comparing your branch with the correct base branch

2021-04-13 11:55 UTC, shubhamtibra submitted a review, later dismissed

2021-04-13 11:59 UTC, shubhamtibra commented on webplugin/js/app/mck-sidebox-1.0.js
> +                        lazy_images.forEach(img => {
```suggestion
                        lazy_images.forEach(function (img) {
```

2021-04-14 05:13 UTC, shubhamtibra submitted a review, later dismissed

2021-04-15 13:24 UTC, devashishmamgain requested changes

2021-04-15 13:24 UTC, devashishmamgain commented on webplugin/js/app/kommunicate-ui.js
> +            if (err) throw err;
use { even if it is one line

2021-04-15 13:24 UTC, devashishmamgain commented on webplugin/js/app/kommunicate-ui.js
> +            },15*60*1000);
replace it with constant

2021-04-15 13:24 UTC, devashishmamgain commented on webplugin/js/app/mck-sidebox-1.0.js
> +                    KommunicateUI.getUrlFromBlobKey(blobKey, function(err, url){
is this code same as the one added in kommunicate-ui? can this be made common?

2021-04-15 13:24 UTC, devashishmamgain commented on webplugin/js/app/mck-sidebox-1.0.js
> +                        var lazy_images = document.querySelectorAll('img.lazy_image');
use same naming convention as used at other places in javascript

2021-04-15 13:24 UTC, devashishmamgain commented on webplugin/js/app/mck-sidebox-1.0.js
> +                                        '"><img class="lazy_image" src="' +
i guess we are using - in css naming

2021-04-16 04:08 UTC, hardikparashar approved these changes

2021-04-17 20:18 UTC, devashishmamgain requested changes
couldn't find the changes related to comment which were resolved

2021-04-17 20:18 UTC, devashishmamgain commented on webplugin/js/app/kommunicate-ui.js
> +            },15*60*1000);
constant is not added, is it marked as resolved by mistake, or changes are not yet pushed to repo?

2021-04-18 03:46 UTC, Prochnost55 commented
> couldn't find the changes related to comment which were resolved

changes weren't pushed as I was waiting for image placeholder cdn url to work.

as of now committed the changes.
will update the URL once I get it

2021-04-18 17:43 UTC, devashishmamgain submitted a review, later dismissed

2021-04-19 07:51 UTC, devashishmamgain approved these changes

2021-04-19 07:52 UTC, shubhamtibra approved these changes

2021-04-19 10:44 UTC, hardikparashar approved these changes

2021-04-23 06:52 UTC, merged