FW-2353 If both msg and image is sent from dashboard, text is not coming in widget
Kommunicate-io/Kommunicate-Web-SDK pull request #701
Opened 2021-06-29 05:21 UTC by ChannuBS

### What do you want to achieve?
-If both msg and image is sent from the dashboard, the text is not coming in the widget

### PR Checklist

- [x] I have tested it locally and all functionalities are working fine.
- [ ] I have compared it with mocks and all design elements are the same.
- [ ] I have tested it in IE Browser.

### How was the code tested?

- add any attachment with a text message in the dashboard and chat widget side and send them
- we can receive the attachment data with text message 
![Screenshot 2021-06-29 at 10 48 59 AM](https://user-images.githubusercontent.com/82803597/123741426-a992e500-d8c7-11eb-91da-744f88f44243.png)

### What new thing you came across while writing this code? 
-

### In case you fixed a bug then please describe the root cause of it? 
-

NOTE: Make sure you're comparing your branch with the correct base branch

2021-06-29 05:30 UTC, devashishmamgain requested changes

2021-06-29 05:30 UTC, devashishmamgain commented on webplugin/css/app/mck-sidebox-1.0.css
> +.message-class-left {
use some other naming, remove class and also see alternative for left
reason is that in RTL what comes on left will be on right side, and this naming might confuse us in future.

2021-06-29 11:11 UTC, devashishmamgain requested changes

2021-06-29 11:11 UTC, devashishmamgain commented on webplugin/js/app/mck-sidebox-1.0.js
> +                var kmAttchMsg= ''
add ;

2021-06-29 11:11 UTC, devashishmamgain commented on webplugin/js/app/mck-sidebox-1.0.js
> +                    if (kmAttchMsg === 'km-attach-msg') {
code inside the if else looks same, figure out a better way to implement it with minimal code and without repeating

2021-06-29 13:38 UTC, devashishmamgain submitted a review, later dismissed

2021-06-29 13:38 UTC, devashishmamgain commented on webplugin/js/app/mck-sidebox-1.0.js
> +                var kmAttchMsg= '';
add space before =

2021-06-29 14:13 UTC, devashishmamgain approved these changes

2021-06-29 16:17 UTC, Ojashwa reviewed
- Getting this type of UI after scrolling in the chat window.
---
https://user-images.githubusercontent.com/22856546/123832897-73834e80-d923-11eb-8141-c7cb68ea8a82.mov

2021-06-30 06:53 UTC, Ojashwa approved these changes

2021-06-30 06:54 UTC, Prochnost55 approved these changes

2021-07-02 13:38 UTC, merged