[WIP] Load Plugin from Shopify Url
Kommunicate-io/Kommunicate-Web-SDK pull request #747
Opened 2021-08-09 06:48 UTC by shubhamtibra

### What do you want to achieve?
-

### PR Checklist

- [ ] I have tested it locally and all functionalities are working fine.
- [ ] I have compared it with mocks and all design elements are the same.
- [ ] I have tested it in IE Browser.

### How was the code tested?

-

### What new thing you came across while writing this code? 
-

### In case you fixed a bug then please describe the root cause of it? 
-

NOTE: Make sure you're comparing your branch with the correct base branch

2021-08-09 12:18 UTC, devashishmamgain requested changes

2021-08-09 13:43 UTC, shubhamtibra commented on webplugin/js/app/mck-app.js
> +        else if (data.shopUrl) {
The Flow will be:
1. Customer clicks "Install App" in Shopify
2. Customer gets asked Permissions
3. Customer is Redirected to dashboard for login/signup
4. Customer need to enable Chat Widget in Theme Editor in Shopify (this step will be mandatory for all new apps in Shopify)

Customer will not have to add the url himself

2021-08-10 04:19 UTC, shubhamtibra commented on webplugin/js/app/mck-app.js
> +            (navigator.userAgent.indexOf('MSIE') !== -1 ||
The existing code will also break the plugin if sentry throws error. Added a try catch just to be sure.

2021-08-10 04:20 UTC, shubhamtibra commented on webplugin/js/app/mck-app.js
> +        data.shopUrl = applozic._globals.shopUrl;
Added

2021-08-10 04:39 UTC, devashishmamgain submitted a review, later dismissed

2021-08-10 05:49 UTC, devashishmamgain approved these changes

2021-08-11 04:29 UTC, Prochnost55 approved these changes

2021-08-13 12:40 UTC, merged