FW-2294 Show categories in FAQ within chat widget
Kommunicate-io/Kommunicate-Web-SDK pull request #751
Opened 2021-08-13 16:50 UTC by Prochnost55

### What do you want to achieve?
- Add a section in FAQ where the user will see categories as shown in helpcenter

### PR Checklist

- [x] I have tested it locally and all functionalities are working fine.
- [x] I have compared it with mocks and all design elements are the same.
- [ ] I have tested it in IE Browser.

### How was the code tested?

- Go to faq
- various categories should appear

### What new thing you came across while writing this code? 
-

### In case you fixed a bug then please describe the root cause of it? 
-

NOTE: Make sure you're comparing your branch with the correct base branch

2021-08-14 05:25 UTC, devashishmamgain commented
@Prochnost55 is it deployed anywhere for testing? Or can you attach screenshot of it

2021-08-14 05:49 UTC, Prochnost55 commented
> @Prochnost55 is it deployed anywhere for testing? Or can you attach screenshot of it

Add a screen recording

2021-08-14 06:05 UTC, devashishmamgain requested changes

2021-08-14 06:05 UTC, devashishmamgain commented on webplugin/js/app/kommunicate-ui.js
> +                    $applozic('#km-faqdiv')
what is common between all these elements may be parent container, or something else? if not, then can we make something common such as adding a specific class
then replace this code with one just one of code that add and remove class based on that common identifer.

2021-08-14 06:05 UTC, devashishmamgain commented on webplugin/js/app/kommunicate-ui.js
> +                            $applozic('#km-contact-search-input-box')
same comment as above

2021-08-16 07:38 UTC, Prochnost55 commented
Used modifyClassList function to make code cleaner.
Also, added faq-common and km-faqdiv to toggle FAQ

2021-08-16 07:49 UTC, devashishmamgain approved these changes

2021-08-17 05:17 UTC, ChannuBS submitted a review, later dismissed

2021-08-17 06:00 UTC, ChannuBS approved these changes

2021-08-17 06:07 UTC, devashishmamgain approved these changes

2021-08-18 11:47 UTC, merged