FW-2690 Remove cdn.applozic.com.com from km chat widget
Kommunicate-io/Kommunicate-Web-SDK pull request #775
Opened 2021-09-16 06:21 UTC by Ojashwa

### What do you want to achieve?
- Remove `cdn.applozic.com.com` from km chat widget.

### PR Checklist

- [x] I have tested it locally and all functionalities are working fine.
- [ ] I have compared it with mocks and all design elements are the same.
- [x] I have tested it in IE Browser.

### How was the code tested?

- Check for basic functionality in the chat widget.

### What new thing you came across while writing this code? 
-

### In case you fixed a bug then please describe the root cause of it? 
-

NOTE: Make sure you're comparing your branch with the correct base branch

2021-09-16 07:03 UTC, devashishmamgain requested changes
what's the reason for this? why to remove from CDN. infact we should be adding more and more files to CDN to improve the performance.

@Ojashwa @Prochnost55

2021-09-16 07:05 UTC, devashishmamgain commented
move it to Kommunicate CDN

2021-09-16 13:02 UTC, devashishmamgain approved these changes

2021-09-17 05:53 UTC, Prochnost55 approved these changes

2021-09-20 10:08 UTC, merged