[TD-2634] Block Conversation on dashboard for Zopim Users
Kommunicate-io/Kommunicate-Web-SDK pull request #873
Opened 2022-05-16 06:23 UTC by pranavp99

### What do you want to achieve?
-

### PR Checklist

- [ ] I have tested it locally and all functionalities are working fine.
- [ ] I have compared it with mocks and all design elements are the same.
- [ ] I have tested it in IE Browser.

### How was the code tested?

-ran local script

### What new thing you came across while writing this code? 
-

### In case you fixed a bug then please describe the root cause of it? 
-

NOTE: Make sure you're comparing your branch with the correct base branch

2022-05-16 06:25 UTC, gargshantnu commented on webplugin/js/app/zendesk-chat-service.js
> +        }
formatting

2022-05-16 06:34 UTC, gargshantnu commented on webplugin/js/app/zendesk-chat-service.js
> +        Kommunicate.updateConversationMetadata(conversationInfo);
use some formatter extension in VS code, and before commit do a formatting.
global spacing of file is 4 spaces.

2022-05-16 06:35 UTC, gargshantnu commented
also, have you not tested this code?
update PR description properly
![Screenshot 2022-05-16 at 12 05 22 PM](https://user-images.githubusercontent.com/23008972/168533076-9f36b812-2308-4456-bfc9-64e766589ac1.png)

2022-05-16 07:38 UTC, gargshantnu submitted a review, later dismissed

2022-05-17 05:10 UTC, Prochnost55 commented
Why is this pr filed for master?

2022-05-17 05:35 UTC, pranavp99 commented
its filed for TD-2634

2022-05-24 04:38 UTC, Prochnost55 approved these changes

2022-05-24 05:03 UTC, Prochnost55 commented
@pranavp99 is it filed for TD-2634 or master?

2022-05-24 05:04 UTC, Prochnost55 requested changes
file the pr correctly
the base needs to be development

2022-05-24 06:08 UTC, closed without merging