Fixed Zendesk End Chat Resolution bug
Kommunicate-io/Kommunicate-Web-SDK pull request #874
Opened 2022-05-17 04:54 UTC by raj5036

### What do you want to achieve?
- Fixed Zendesk End Chat Resolution bug

### PR Checklist

- [X] I have tested it locally and all functionalities are working fine.

### How was the code tested?

- Tested locally.

2022-05-17 05:25 UTC, Prochnost55 requested changes

2022-05-17 05:25 UTC, Prochnost55 commented on webplugin/js/app/mck-sidebox-1.0.js
> +            '<div class="km-csat-skeleton"> <div class="mck-rated"> <span id="mck-resolved-text" class=${isConversationResolvedFromZendesk ? "" : "n-vis"}>' +
this will not work in IE

2022-05-17 05:25 UTC, Prochnost55 commented on webplugin/js/app/zendesk-chat-service.js
> +        KommunicateUI.isConversationResolvedFromZendesk= true;
formating

2022-05-17 05:25 UTC, Prochnost55 commented on webplugin/css/app/mck-sidebox-1.0.css
> +/* .km-csat-skeleton .mck-rated:after,
if not required we can remove this

2022-05-18 13:37 UTC, gargshantnu commented on webplugin/js/app/mck-sidebox-1.0.js
> +                        if (KommunicateUI.isConversationResolvedFromZendesk == false) {
```suggestion
                        if (!KommunicateUI.isConversationResolvedFromZendesk) {
```

2022-05-19 04:13 UTC, gargshantnu approved these changes

2022-05-25 03:58 UTC, Prochnost55 approved these changes

2022-05-26 09:54 UTC, merged