[TD-2768]Add phone number in zopim chat(1)
Kommunicate-io/Kommunicate-Web-SDK pull request #911
Opened 2022-07-20 06:20 UTC by pranavp99

### What do you want to achieve?
-Phone number details should be passed to zendesk zopim.

### PR Checklist

- [ ] I have tested it locally and all functionalities are working fine.
- [ ] I have compared it with mocks and all design elements are the same.
- [ ] I have tested it in IE Browser.

### How was the code tested?

-check if entered phone number is similar to the phone contact in zopim user.

### What new thing you came across while writing this code? 
-

### In case you fixed a bug then please describe the root cause of it? 
-

NOTE: Make sure you're comparing your branch with the correct base branch

2022-07-20 06:53 UTC, gargshantnu commented on webplugin/js/app/zendesk-chat-service.js
> +                });
i guess this will trigger for each incoming msgs?

2022-07-21 06:47 UTC, gargshantnu commented on webplugin/js/app/zendesk-chat-service.js
> +            var check = 1;
instead of check, use some boolean with some meaningful name in this context.

2022-07-21 07:27 UTC, gargshantnu submitted a review, later dismissed

2022-07-21 07:37 UTC, mukeshthawani approved these changes

2022-07-21 07:39 UTC, devashishmamgain requested changes

2022-07-21 07:39 UTC, devashishmamgain commented on webplugin/js/app/zendesk-chat-service.js
> +    var numberUpdatedInZopim = false;
this will be false again in every page refresh and that means we will keep calling the API again?

2022-07-21 07:40 UTC, devashishmamgain approved these changes

2022-07-21 07:42 UTC, devashishmamgain requested changes
added comment

2022-07-21 11:09 UTC, gargshantnu requested changes

2022-07-21 11:09 UTC, gargshantnu commented on webplugin/js/app/zendesk-chat-service.js
> +                }
can you move this logic to some other function whose job is just to do all this

2022-07-21 11:37 UTC, gargshantnu approved these changes

2022-07-21 11:55 UTC, closed without merging

2022-07-21 12:08 UTC, pranavp99 commented
closed this PR and raised a new one as base branch was master instead of development
https://github.com/Kommunicate-io/Kommunicate-Web-SDK/pull/915 link to the new PR