The bot icon disappear after the button is clicked [Prod Bug]
Kommunicate-io/Kommunicate-Web-SDK pull request #973
Opened 2022-11-04 18:39 UTC by Sanjeevsinghnegi

### What do you want to achieve?
- The bot icon disappears after the button is clicked - hidePostCta Enable

### PR Checklist

- [x] I have tested it locally and all functionalities are working fine.
- [ ] I have compared it with mocks and all design elements are the same.
- [ ] I have tested it in IE Browser.

### How was the code tested?

-

### What new thing you came across while writing this code? 
-

### In case you fixed a bug then please describe the root cause of it? 
-

NOTE: Make sure you're comparing your branch with the correct base branch

2022-11-05 06:44 UTC, Prochnost55 requested changes

2022-11-05 06:44 UTC, Prochnost55 commented on webplugin/js/app/kommunicate.js
> +        var kmClubbingChild = element.closest('.mck-message-inner').children;
closest is not supported in IE 11
hence widget will stop working in IE.

2022-11-05 06:52 UTC, anujpanwar01 commented on webplugin/js/app/kommunicate.js
> +            Array.from(kmClubbingChild).find(child => {
Array.from not supported in IE 11

2022-11-05 10:14 UTC, Sanjeevsinghnegi commented
@Prochnost55 update the strategy to target the class

2022-11-05 10:19 UTC, anujpanwar01 submitted a review, later dismissed

2022-11-05 10:22 UTC, anujpanwar01 approved these changes

2022-11-05 10:32 UTC, Prochnost55 approved these changes

2022-11-05 10:35 UTC, anujpanwar01 submitted a review, later dismissed

2022-11-05 11:43 UTC, anujpanwar01 submitted a review, later dismissed

2022-11-05 11:48 UTC, Prochnost55 approved these changes

2022-11-07 05:17 UTC, Prochnost55 approved these changes

2022-11-07 05:25 UTC, anujpanwar01 approved these changes

2022-11-07 09:18 UTC, merged