Fixed Bug for CreatedAt giving Undefined
Kommunicate-io/Kommunicate-Web-SDK pull request #996
Opened 2022-12-16 16:04 UTC by Sanjeevsinghnegi

### What do you want to achieve?
- Fixed Bug for CreatedAt giving Undefined

### PR Checklist

- [x] I have tested it locally and all functionalities are working fine.
- [ ] I have compared it with mocks and all design elements are the same.
- [ ] I have tested it in IE Browser.

### How was the code tested?

-

### ScreenShot
- Bug
![Screenshot 2022-12-16 at 9 29 50 PM](https://user-images.githubusercontent.com/66241555/208138949-398f179f-fb70-4054-b871-864f5dbedde4.png)

### In case you fixed a bug then please describe the root cause of it. 
- there is no data check and we are getting undefined 

NOTE: Make sure you're comparing your branch with the correct base branch

2022-12-16 16:27 UTC, devashishmamgain reviewed
not sure if it will fix the issue, as far as i understand error is coming for groupFeeds to be empty and not data as undefined.
is it tested by reproducing?

2022-12-16 20:15 UTC, devashishmamgain requested changes

2022-12-16 20:15 UTC, devashishmamgain commented on webplugin/js/app/mck-sidebox-1.0.js
> +                        CURRENT_GROUP_DATA.createdAt = data && data.groupFeeds[0].createdAtTime;
data &&
                            data.groupFeeds[0] &&

same as the code below it at line no. 6395

2022-12-17 06:48 UTC, Sanjeevsinghnegi commented
Closing this as @Prochnost55 also fixed the same bug

2022-12-17 06:48 UTC, closed without merging